spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gymnoteapi
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: GymNoteApi

security:
  jwt:
    secretKey: ${SECRET_KEY}
    accessTokenExpiration: 900000 # 15 minutes in milliseconds
    refreshTokenExpiration: 604800000 # 7 days in milliseconds