spring:
  datasource:
    url: jdbc:postgresql://db:5432/gymnote
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    gymnote.gymnoteapi: DEBUG